# Use official Node.js image
FROM node:18-slim

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install --only=production

# Bundle app source
COPY . .

# Bind to port 8080 (default for Cloud Run)
EXPOSE 8080

# Define command to run the app
CMD [ "node", "server.js" ]
